[package]
name = "aes"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
lazy_static = "0.2"
num = "0.1"

[dev-dependencies]
rust-crypto = "0.2"
openssl = { version = "0.7", features = [ "aes_ctr", "aes_xts" ] }
rand = "0.3"
